## HW4 Q3
**Bakhshande 98522157**

In [ ]:
import numpy as np
import pandas as pd
import random as rd
from random import randint
import matplotlib.pyplot as plt

## Initialization

In [ ]:
threshold = 25  

rock = np.array([1,2,3,4,5,6,7,8])
weight = np.array([2,4,1,3,5,1,7,4])
value = np.array([30,10,20,50,70,15,40,25])

print('Rock --> Weight --> Value')
for i in range(rock.shape[0]):
    print('{} ------> {} ------> {}'.format(rock[i], weight[i], value[i]))

Rock --> Weight --> Value
1 ------> 2 ------> 30
2 ------> 4 ------> 10
3 ------> 1 ------> 20
4 ------> 3 ------> 50
5 ------> 5 ------> 70
6 ------> 1 ------> 15
7 ------> 7 ------> 40
8 ------> 4 ------> 25


In [ ]:
chromo = 8
size_of_population = (chromo, rock.shape[0])
print('Size Of Population is: {}'.format(size_of_population))

initial = np.random.randint(2, size = size_of_population)
initial = initial.astype(int)
generations = 50
print('Initial Population is: \n{}'.format(initial))

Size Of Population is: (8, 8)
Initial Population is: 
[[0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]
 [0 1 1 0 1 0 0 0]
 [1 0 0 1 1 0 0 1]
 [1 1 1 1 0 0 0 0]
 [0 0 1 0 1 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 1 0 1 0 0 0]]


## Fitness Function

In [ ]:
def fit(weight, value, pop, threshold):

    fitness = np.empty(pop.shape[0])
    
    for i in range(pop.shape[0]):
        S1 = np.sum(pop[i] * value)
        S2 = np.sum(pop[i] * weight)
        if S2 <= threshold:
            fitness[i] = S1
        else :
            fitness[i] = 0 

    return fitness.astype(int)  

## Selecting Function

In [ ]:
def selecting(fi, num, pop):

    parents = np.empty((num, pop.shape[1]))
    fit = list(fi)

    for i in range(num):
        maximum_fit = np.where(fit == np.max(fit))
        parents[i,:] = pop[maximum_fit[0][0], :]
        fit[maximum_fit[0][0]] = -99
        
    return parents

## One-Point Crossover

In [ ]:
def crossover(par, number): 

    i=0
    rate_of_cross = 0.8
    point_of_cross = int(par.shape[1]/2)
    res = np.empty((number, par.shape[1]))

    while (par.shape[0] < number):
        x = rd.random()
        par1 = (i+1)%par.shape[0]
        par2 = i%par.shape[0]

        if x > rate_of_cross:
            continue
            
        par2 = i%par.shape[0]
        par1 = (i+1)%par.shape[0]
        res[i,0:point_of_cross] = par[par2,0:point_of_cross]
        res[i,point_of_cross:] = par[par1,point_of_cross:]
        i=+1

    return res    

## Mutation

In [ ]:
def mutation(df):

    rate_of_mu = 0.4
    mu = np.empty((df.shape)) 

    for i in range(mu.shape[0]):
        mu[i,:] = df[i,:]
        val = rd.random()
        
        if val > rate_of_mu:
            continue

        val_rand = randint(0,df.shape[1]-1)    
        if mu[i,val_rand] == 0 :
            mu[i,val_rand] = 1
        else :
            mu[i,val_rand] = 0

    return mu  

In [ ]:
def optimize(weight, value, pop, size, gens, threshold):

    par_numbers = int(size[0]/2)
    nums = size[0] - par_numbers 
    parm, fitn = [], []

    for i in range(gens):
        asd = fit(weight, value, pop, threshold)
        fitn.append(asd)
        paa = selecting(asd, par_numbers, pop)
        fg = crossover(paa, nums)
        yu = mutation(fg)
        pop[0:paa.shape[0], :] = paa
        pop[paa.shape[0]:, :] = yu
        
    print('Chromosomes of Last generation are: \n{}\n'.format(pop)) 

    asdef = fit(weight, value, pop, threshold)      
    max_fitness = np.where(asdef == np.max(asdef))
    parm.append(pop[max_fitness[0][0],:])

    return parm, fitn

In [ ]:
params, kh = optimize(weight, value, initial, size_of_population, generations, threshold)
print('Result Choromosome is: {}'.format(params))

se = rock * params
array = ['زمرد', 'نقره', 'یاقوت', 'الماس', 'برلیان', 'فیروزه', 'عتیق', 'کهربا']
print('Selected Rocks are:')
for i in range(se.shape[1]):
  if se[0][i] != 0:
     print('{}: {}'.format(se[0][i], array[i]))

Chromosomes of Last generation are: 
[[1 0 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1]
 [1 0 1 1 1 1 0 1]
 [1 0 1 0 1 1 1 1]]

Result Choromosome is: [array([1, 0, 1, 1, 1, 1, 1, 1])]
Selected Rocks are:
1: زمرد
3: یاقوت
4: الماس
5: برلیان
6: فیروزه
7: عتیق
8: کهربا
